### PR TITLE
Add Markdown Link support for topic changes

### PR DESCRIPTION
**Pull request by chrisbraucker**
First ever modification to a chromium extension.

I love your extension. It gives so much needed configurability to slack.

I tried to copy your style as closely as possible. If the modification should rather be done in the `else if` branch below my point of entry, do tell :)

I _guess_ this doesn't have to be replicated in the websocket section because the topic change should be synchronous.

### CODE REVIEW

**Comment by g3rv4** [comment]
fancy! thank you very much!

I'm going to work on refactoring the whole thing a bit more so that it's easier to maintain (it was born as a bunch of userscripts together and I guess it shows).

I'll review this today and if it works across all browsers, let's ship it!

**Review by g3rv4 — COMMENTED** [review]
Thank you very much! it works like a charm!

**Comment by g3rv4** [comment]
Shipped on v1.3.7. Hope [this is your twitter account](https://twitter.com/g3rv4/status/1045423445838884866) :)

**Comment by chrisbraucker** [comment]
Haha, I updated and tested it the minute I learned about the new version.
And thanks for the shoutout ;) Always happy to contribute

**Pull request merged**
